[build]
  command = "bundle exec jekyll build"
  publish = "_site/"
[context.production]
  environment = { JEKYLL_ENV = "production" }
[[plugins]]
  package = "netlify-plugin-checklinks"
[[plugins]]
  package = "netlify-plugin-jekyll-cache"
