# https://www.netlifycms.org/docs/jekyll/
backend:
  name: github
  repo: fauno/factastichealth_website
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
    - label: 'Layout'
      name: 'layout'
      widget: 'hidden'
      default: 'post'
    - label: 'Image'
      name: 'image'
      widget: 'image'
      allow_multiple: false
      media_library:
        allow_multiple: false
    - label: 'Title'
      name: 'title'
      widget: 'string'
    - label: 'Publish Date'
      name: 'date'
      widget: 'datetime'
    - label: 'Body'
      name: 'body'
      widget: 'markdown'
    - label: 'Categories'
      name: 'categories'
      widget: 'list'
    - label: 'Tags'
      name: 'tags'
      widget: 'list'
  - name: 'pages'
    label: 'Pages'
    folder: '_pages/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
    - label: 'Layout'
      name: 'layout'
      widget: 'hidden'
      default: 'page'
    - label: 'Title'
      name: 'title'
      widget: 'string'
    - label: 'Publish Date'
      name: 'date'
      widget: 'datetime'
    - label: 'Body'
      name: 'body'
      widget: 'markdown'
    - label: 'Appears on footer'
      name: 'footer'
      widget: 'boolean'
      default: false
